### ISSUE TITLE
Photoshop CC extension showing > 100% progress

### ISSUE THREAD

**Issue by matthojo** [avocode/avocode#101]
**Reproducibility:** High
**Description:** When exporting a Photoshop document the extension displays > 100%.
**Steps to reproduce:** Export an document
**Expected result:** Stop putting in the extra work, there really is no need :wink: 
**Actual result:**
![screen shot 2015-01-22 at 11 59 50](https://cloud.githubusercontent.com/assets/367517/5855274/3f1a5266-a22e-11e4-8ef9-425841b17f19.png)
**OS and app versions:**
* Mac OS X 10.10
* Photoshop CC 2014.2.2
* Avocode extension 1.0.0

**Comment by marekhrabe** [comment]
That is the secret why Avocode can give you even more than you expected! :D

I fixed that error few hours ago, it will be shipped in extension 1.0.1

Btw: nice structred report. Thumbs up :+1:

**Comment by matthojo** [comment]
Nice work.

No problem :)

**Comment by kupcza** [comment]
Downloaded latest version of extension and still getting over 100%

![Image of over](https://dl.dropboxusercontent.com/spa/7umqxezjfny1dx9/8esw3fvq.png)
