### ISSUE TITLE
Uploading from Dropbox doesn't work

### ISSUE THREAD

**Issue by zenwarr** [avocode/avocode#1314]
When I try to upload a psd file from Dropbox, the file is added to 'pending design' panel and gets "Queued" status, but stays with this status forever. After reloading the page the file just disappears from "pending" panel.

**Comment by rychlis** [comment]
Thanks for the report, we can reproduce the issue. It seems Dropbox changed something in their API which broke our processing code. We should be able to fix this very soon

**Comment by rychlis** [comment]
We have just deployed fix for this issue. Thanks for your report!

**Comment by zenwarr** [comment]
Sorry to say, but it looks like a problem still exists. My fault is that I didn't investigate this issue much.
It appears that the issue is caused by long file paths that contain non-english letters. Dropbox chooser returns urlencoded string, so each non-english letter is converted to at least three, and path length grows significantly.

In my test case, I tried to import a file at the following location on my Dropbox:
/Приложения/GImporter/ААААА/Сервис/Возврат/ааааа_возврат.psd
Dropbox returns an URL to access the file that looks like this:
https://dl.dropboxusercontent.com/1/view/lsfjlsl34lkjlkl/%2F%D0%9F%D1%80%D0%B8%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D1%8F%2FGImporter%2F%D0%90%D0%90%D0%90%D0%90%D0%90%2F%D0%A1%D0%B5%D1%80%D0%B2%D0%B8%D1%81%2F%D0%92%D0%BE%D0%B7%D0%B2%D1%80%D0%B0%D1%82%2F%D0%B0%D0%B0%D0%B0%D0%B0%D0%B0_%D0%B2%D0%BE%D0%B7%D0%B2%D1%80%D0%B0%D1%82.psd
And Avocode tries to download a file at this URL, but fails:
![avocode-issue](https://cloud.githubusercontent.com/assets/1969391/23715130/cf5715ae-0455-11e7-973f-e3de3939f4a5.png)

![avocode-issue-error](https://cloud.githubusercontent.com/assets/1969391/23715423/cb29f2fc-0456-11e7-8138-2bbc32a55799.png)

I have tried to rename the file, getting rid of non-english long paths, and it works! After this, file import is done correctly.

**Comment by rychlis** [comment]
ok the issue that we have fixed was unrelated to your issue. Thanks for the screenshot, this explains the issue very well and it should be pretty easy to fix :)

**Comment by rychlis** [comment]
We've just bumped the limit to 1000 characters which should fix your issue
