### ISSUE TITLE
Few UI bugs in 2.15

### ISSUE THREAD

**Issue by evanre** [avocode/avocode#1623]
* **Version**: 2.15.2
* **Web/Desktop**: Desktop
* **Platform/Browser**: Windows 10, Manjaro Linux (Arch Linux + xfce)

Hey guys. There is couple bugs I've noticed from the last big update. So far as i'm a front-end developer, and Avocode is a web app, I've got ideas why this could happen.

1. When hovering tool buttons, cursor changes only on buttons but not icons (hover edges of the button - cursor: pointer, hover the icon - cursor: default).
2. If I hide the Toolbar (It's a mockery to hide this dummy bar each time I opening design. It takes a lot of space and really have no use during inspecting designs (99% of my work in Avocode)). So, when I hide the toolbar, I can't click on first tool button and first two layers in list (on the top left corner). I think it's because of there is some some overlay element with position: fixed; that didn't removed when hiding the tool box.

Here is a [small video](https://goo.gl/rdN6AS) to describe the bugs If you didn't understand something (my English isn't perfect so I assume this))) 

PS. Maybe you guys should to think about how to store and sync user settings? Each time I open a new design i need to hide tool bar and switch css variables to scss. Also I need manually add variables for each project on all devices I'm working with.

**Comment by jakubzitny** [comment]
Thanks for the detailed report @evanre. I get your point(s). We'll have look at the issues 1) and 2) and also at saving the code panel language. As for the last thing, we are already in progress of implementing syncing the variables across devices, so we'll let you know when it's ready 🙂 

Please, let us know if you have any other enhancements ideas or any other problems with Avocode.

**Comment by evanre** [comment]
@jakubzitny That's great news! Thank you guys for creating a wonderful app!

**Comment by i-v-k** [comment]
Same problem as described in issue 2.

Version: 2.15.5
Web/Desktop: Desktop
Platform: win32 (Win 10 64bit)
Avocode UID: 112740

**Comment by jakubzitny** [comment]
Hi guys, we've released the ability to sync variables across devices and team members in `2.16.0`. We will continue working on other problems from this issue in upcoming weeks.

**Comment by evanre** [comment]
@jakubzitny Hi guys. Are you kidding me? :-) Where is View-tools trigger in last update?? You didn't fix the bug I've described month ago and you decided just remove this trigger? This panel eats usable space and doesn't anything usefull. I'm working on 15.4 inch notebook, and it's looks ridiculous to me. You could make full screen mode and that would be much better  -_-
![1366*768 screen shot of strange Avocode UI](https://img2.brain4.photobox.com/922821459a0a049586c27ba7c2b61c4e19459e74d94da8554764ef3b2146ffd62b908043.jpg)

**Comment by i-v-k** [comment]
I completely agree with evanre.
@jakubzitny it's ridiculous, first time I saw it I didn't believe my eyes you just removed menu option instead of fixing the bug.

**Comment by jakubzitny** [comment]
Sorry for missing this guys. We actually had some good intentions behind removing the option, but we'll talk about it with team next week and come back to you. The four top bars on Windows and Linux don't look really good indeed 😅

**Comment by jakubzitny** [comment]
So the thing here is that the top bar is now global for the whole app. We don't want users to lose the ability to log out / switch org / share a design / search / switch to parent project or to comment mode.

We're considering to try out some kind of full-screen mode, where you would not see the application window bar, the menu bar nor the tab bar. Also this top bar we're talking about would be hidden and only accessed after mouse move to the top. Would that work for you? What else would you like to see in such a mode?

Another thing we're considering is to hide the menu bar and application bar altogether. You would lose the access to menu though. Almost all of the menu items are already places into the app itself (so it works with our web version as well). Would you miss the menu if we were to hide it?

**Comment by i-v-k** [comment]
"Another thing we're considering is to hide the menu bar and application bar altogether"
sounds good to me!

**Comment by evanre** [comment]
Hi, any change that give more working space is work for me. Thanks.

Full screen is excellent idea 👍

**Comment by vojtatranta** [comment]
@evanre you can now set default code template language on the project since `2.21.0`
