### ISSUE TITLE
Linux | Use dark GTK+ theme by default

### ISSUE THREAD

**Issue by nikolowry** [avocode/avocode#176]
Please consider enabling the "dark-theme" and "auto-hide-menu-bar" for Linux by default.  I edited the src to enable it on mine.  Atom Text Editor has enabled both by default.

Dark:
![Dark](https://s3.amazonaws.com/f.cl.ly/items/3P2K1L1l2O1r0k32351N/Screenshot%20from%202015-03-15%2013-42-59.png)

Light:
![Light](https://s3.amazonaws.com/f.cl.ly/items/3E2X423N0C352p1k0b1U/Screenshot%20from%202015-03-15%2013-41-32.png)

**Comment by petrbrzek** [comment]
Related to #177. We need to update atom-shell.

**Comment by rychlis** [comment]
Looks like it's fixed in 2.2.0

**Comment by nikolowry** [comment]
Still showing the ugly light toolbar and now the source code has been converted to binary.  While using electron and chrome libraries probably accelerated cross-platform development - it is a real hinderance in integrating into linux. It's such a distraction when I open an App and it doesn't match my desktop.  Not to mention how resource intensive the app's are.

Oh well.

**Comment by rychlis** [comment]
It worked for me when using a dark theme in XFCE, that's why i closed the issue. I think we we can add a way to use the dark theme in settings or make it possible for the user to change the css maybe. Or if you want to experiment, you should be able to extract the asar (it's not binary but a tar-like archive) with the [asar tool](https://github.com/atom/asar) and change the source.
