### ISSUE TITLE
 Syncing updates seems broken with new version of sketch

### ISSUE THREAD

**Issue by ajilderda** [avocode/avocode#491]
IMPORTANT: Please try to describe how did it happen.
In step 3, uploading layers, Avocode crashes with the follow error:

-----
Sketch Exporter 2.1.1 running in Sketch 3.4
```
TypeError: Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:313:15)
    at /Users/Andre/…/avocode-exporter/lib/image-exporter.js:1:297
    at Object.oncomplete (fs.js:107:15)
```

**Comment by jankuca** [comment]
Duplicate of #472

**Comment by marekhrabe** [comment]
We just released a new version of extension that supports Sketch 3.4. Download here https://manager.avocode.com/downloads/

**Comment by NewMediaStudio** [comment]
Error persists:

-----
Sketch Exporter 2.1.3 running in Sketch 3.4
```
TypeError: Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:313:15)
    at /Users/val/…/avocode-exporter/lib/image-exporter.js:1:297
    at Object.oncomplete (fs.js:107:15)
