### ISSUE TITLE
Avocode Sync error: Sketch 3.5.1 [Command Failed]

### ISSUE THREAD

**Issue by jgribben** [avocode/avocode#643]
Will use Sketch 3.4 work around. Chasing an update as last news of this error was 2 days ago. 

This error is appearing every time I try to sync to Avocode from Sketch 3.5.1. I have tried multiple files, multiple locations. Updated Avocode/ sketch, uninstalled and re-installed both. 

![screen shot 2016-01-28 at 4 49 52 pm](https://cloud.githubusercontent.com/assets/16930427/12637229/58af6e0c-c5df-11e5-9726-53ffa8169d51.png)

**Comment by bolekkerous** [comment]
Hello!
We have already released Sketch Extension 3.0.0-prerelease4 with Sketch 3.5 support. Please download the latest version from https://github.com/avocode/avocode/blob/master/sketch-extension-beta.md#installation--update

I am closing this issue as a duplicate, if there would be a problem with the new extension, please follow up on #609

Thank you and sorry for the inconvenience.

**Comment by jgribben** [comment]
New pre release doesn't work. Still getting error saying upload failed try again...

**Comment by bolekkerous** [comment]
Are you sure you are using the prerelease-4? Reinstalling the plugin and Sketch may help.

If it doesn't, could you please send us log files from Sketch to team@avocode.com? Here is a guide on how to get log files (the last paragraph): https://github.com/avocode/avocode/blob/master/sketch-extension-beta.md

Thanks!
