### ISSUE TITLE
Error on upload .psd file

### ISSUE THREAD

**Issue by dzounas** [avocode/avocode#685]
Error occurred while I was uploading project .psd file.
-----
App v.2.5.2
Source UID: 48601
```
Error: invalid stored block lengths
  at Zlib._handle.onerror (zlib.js:345:17)

```

**Comment by dzounas** [comment]
More info: The .psd file is about 150MB and the bug appears at 95%.

**Comment by vojtatranta** [comment]
I see, great. 
Many thanks for this info, we did not know this. I suppose you are running Mac OS X, right?

**Comment by dzounas** [comment]
No problem. And no, I am running Win10.

**Comment by dzounas** [comment]
Also tried to upload another .psd with lower size, about 90MB and still got the same error.

**Comment by vojtatranta** [comment]
Aha, that is also very helpful.
We know that there are troubles on Windows with larger files. We will investigate it.
Many thanks

**Comment by dzounas** [comment]
Hey,
Can I ask how is the progress of fixing the problem? I wanted to try your product to make my work easier but now I cannot do anything because most of psd's I use are over 100MB. And the days go by in the trial period.
Thank you.

**Comment by petrbrzek** [comment]
This error should be now fixed with the latest Avocode 2.5.3. Please try it and let us know.

**Comment by dzounas** [comment]
Hello, sorry I couldn't test it earlier. But it seems like the bug is still there. When I tried to upload bigger file (around 200MB), it crashed again with this info:

App v.2.5.3
Source UID: 147144
```
Error: invalid stored block lengths
    at Zlib._handle.onerror (zlib.js:345:17)
```

Worked fine for smaller file (20MB).

**Comment by petrbrzek** [comment]
Hi, we've released 2.5.4 that should fix this issue. If you still have this problem in the new app, feel free to report it as a new issue.
