### ISSUE TITLE
Bug export image (2.8.1)

### ISSUE THREAD

**Issue by idsampaio** [avocode/avocode#935]
Hi,

When exporting any icon with transparency in .png or .jpg, this is completely white.

![01](https://cloud.githubusercontent.com/assets/20042195/16191007/0833931a-36da-11e6-88cd-0def04c71f0b.png)
![02](https://cloud.githubusercontent.com/assets/20042195/16191008/0853644c-36da-11e6-94e1-8b0083c6f5cb.png)

: /

Thanks

**Comment by jakubzitny** [comment]
Hey @idsampaio, thanks for reporting this.

There might be several issues causing this to happen. Would you be willing to send us the PSD/Sketch of the design to team@avocode.com? We'd inspect it and find the problem.

**Comment by idsampaio** [comment]
Hey @jakubzitny,

I was checking old files in AVOCODE to see if they gave to export and nothing ...

So I created a file (test.sketch) again and sent it to the AVOCODE, which has the same mistake, not exported.

Sketch File: [test.zip](https://github.com/avocode/avocode/files/323453/test.zip)

Thanks

**Comment by akifuygun** [comment]
same issue here.
also having problem exporting gradients as image.

**Comment by jakubzitny** [comment]
Hey guys. Thanks for the info and for sticking with us ;) also for the Sketch file, @idsampaio.

We're currently having some small problems with grouped layers with effects. For your case @idsampaio, when you select the whole group when exporting the icon with the circle, it will export correctly.

We also have a bug in `2.8.1` with exporting circle shapes in some cases. We will release new update `2.8.2` today with fix for it.

I'll leave this open until we're sure everything is correct.

**Comment by jakubzitny** [comment]
Hey, we have just released new update for Avocode and these issues are fixed there. You can upgrade directly in the app or download new version from [avocode.com/download](http://avocode.com/download/).

Let us know if you have any other problems ;)

**Comment by k1sul1** [comment]
I just had this issue. Design created in Sketch, and trying to export a transparent image from a symbol results in an empty exported image. 

I did the "select the whole group when exporting the icon with the circle" part, and manually deselected the unwanted parts and then it worked, though it says I've 4 layers selected.

**Comment by volodymyrlut** [comment]
Still see this issue in 2.14.8
![screen shot 2017-08-28 at 4 47 08 pm](https://user-images.githubusercontent.com/5955048/29776201-968c7d20-8c10-11e7-997b-e9c58f3625f9.png)
![map-g](https://user-images.githubusercontent.com/5955048/29776209-9e7f9cba-8c10-11e7-9332-e68c084f6d5d.png)

**Comment by jakubzitny** [comment]
@volodymyrlut the issue here is that it is not transparent or the preview in Export Assets modal is wrong? 

Fyi, we're redesigning our rendering from scratch and we will be releasing a new version in coming months where all combinations of these issues should be fixed.

**Comment by volodymyrlut** [comment]
@jakubzitny sure, the export output is completely different from preview because of half-transparent layers are not exported.

**Comment by bolekkerous** [comment]
Hey, @volodymyrlut -
thanks for the report - could you please send us the problematic design (or just the problematic part of it) to team@avocode.com?

We'd need the design to investigate the issue properly with our rendering team.

Thanks and sorry for the inconvenience.
